---
- hosts: '*'
  remote_user: root
  become: yes
  roles:
    - vars
    - pre_install
    - security
    - { role: rvm1-ansible,
        tags: ruby,
        become: yes,
        rvm1_rubies: ['ruby-{{ruby_version}}'],
        rvm1_install_flags: '--auto-dotfiles',     # Remove --user-install from defaults
        rvm1_install_path: /usr/local/rvm,         # Set to system location
        rvm1_user: root                            # Need root account to access system location
      }
    - database
    - application
