---
- hosts: '*'
  roles:
    - vars
    - pre_install
    - security
    - ruby
    - database
    - user
    - redis
    - { role: application,  ansible_user: '{{application_name}}' }
    - http_server # httpd / nginx
