- name: Install repository
  yum: name={{ database_repo_url }} state=present
  become: true

- name: Install postgres client
  yum: name={{item.name}} state=latest
  become: true
  with_items:
    - { name: 'postgresql{{ database_version|replace(".", "") }}'}
    - { name: 'postgresql{{ database_version|replace(".", "") }}-devel'}
    - { name: 'python-psycopg2'}

- name: Symlink pg_config to default
  become: true
  file:
    src: /usr/pgsql-{{ database_version }}/bin/pg_config
    dest: /usr/bin/pg_config
    state: link

- name: Create Database
  postgresql_db:
    login_host: '{{ database_host }}'
    login_user: '{{ database_root_user }}'
    login_password: '{{ database_root_password }}'
    name: '{{ database_dbname }}'
    encoding: UTF-8

- name: Create Database User
  postgresql_user:
    login_host: '{{ database_host }}'
    login_user: '{{ database_root_user }}'
    login_password: '{{ database_root_password }}'
    db: '{{ database_dbname }}'
    name: '{{ database_username }}'
    password: '{{ database_password }}'
    priv: "ALL"
