- name: Clone Project Repository
  git:
    repo: '{{application_repo}}'
    dest: '{{application_path}}'
    version: '{{application_branch}}'
    accept_hostkey: yes
  remote_user: '{{application_name}}'

- name: Template database configuration
  template:
    src: database.yml
    dest: '{{ application_path }}/{{application_root}}/config/database.yml'

- name: Install Javascript Runtime
  yum: name={{item.name}} state=latest
  become: true
  when: (javascript_runtime != '')
  with_items:
    - { name: '{{javascript_runtime}}'}

- name: Install/update gems
  bundler:
    state: present
    # deployment_mode: yes
    exclude_groups: 'development,test'
    chdir: '{{ application_path }}/{{application_root}}'

- name: migrate the database
  shell: RAILS_ENV={{ application_environment }} bundle exec rake db:migrate
  args:
    chdir: "{{ application_path }}/{{application_root}}"

- name: Generate secret key
  shell: "RAILS_ENV={{ application_environment }} rake generate_secret_token"
  args:
    chdir: "{{ application_path }}"
