- name: Clone Project Repository
  git:
    repo: '{{application_repo}}'
    dest: '{{application_path}}'
    version: '{{application_branch}}'
    accept_hostkey: yes

- name: Template database configuration
  template:
    src: database.yml
    dest: '{{ application_path }}/{{application_root}}/config/database.yml'

- name: Install/update gems
  bundler:
    state: present
    # deployment_mode: yes
    chdir: '{{ application_path }}/{{application_root}}'

- name: migrate the database
  shell: RAILS_ENV={{ application_environment }} bundle exec rake db:migrate
  args:
    chdir: "{{ application_path }}/{{application_root}}"

- name: Generate secret key
  shell: "RAILS_ENV={{ application_environment }} rake generate_secret_token"
  args:
    chdir: "{{ application_path }}"
