- name: test connection
  ping:
- name: install packages
  yum: name={{item.name}} state=latest
  become: true
  with_items:
    - { name: 'epel-release'}
    - { name: 'vim'}
    - { name: 'firewalld'}
    - { name: 'bash-completion'}
    - { name: 'bash-completion-extras'}
    - { name: 'htop'}
    - { name: 'rsync'}
    - { name: 'git'}
    - { name: 'telnet'}
    - { name: 'gcc-c++'}
    - { name: 'patch'}
    - { name: 'readline'}
    - { name: 'readline-devel'}
    - { name: 'zlib'}
    - { name: 'zlib-devel'}
    - { name: 'libcurl-devel'}
    - { name: 'ImageMagick'}
    - { name: 'ImageMagick-devel'}
    - { name: 'libyaml-devel'}
    - { name: 'libffi-devel'}
    - { name: 'openssl-devel'}
    - { name: 'make'}
    - { name: 'bzip2'}
    - { name: 'autoconf'}
    - { name: 'automake'}
    - { name: 'libtool'}
    - { name: 'bison'}
    - { name: 'mysql-devel'}
    - { name: 'ruby-devel'}
