- name: test connection
  ping:
- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
- name: install packges
  yum: name={{item.name}} state=latest
  with_items:
    - { name: 'bash-completion'}
    - { name: 'bash-completion-extras'}
    - { name: 'htop'}
    - { name: 'git'}
    - { name: 'telnet'}
    - { name: 'gcc-c++'}
    - { name: 'patch'}
    - { name: 'readline'}
    - { name: 'readline-devel'}
    - { name: 'zlib'}
    - { name: 'zlib-devel'}
    - { name: 'libcurl-devel'}
    - { name: 'ImageMagick'}
    - { name: 'ImageMagick-devel'}
    - { name: 'libyaml-devel'}
    - { name: 'libffi-devel'}
    - { name: 'openssl-devel'}
    - { name: 'make'}
    - { name: 'bzip2'}
    - { name: 'autoconf'}
    - { name: 'automake'}
    - { name: 'libtool'}
    - { name: 'bison'}
